export const EXTRACTION_STATUS = {
    IN_QUEUE: 'IN_QUEUE',
    EXTRACTION_IN_PROGRESS: 'EXTRACTION_IN_PROGRESS',
    EXTRACTION_FAILED: 'EXTRACTION_FAILED',
    VALIDATION_PENDING: 'VALIDATION_PENDING',
    VALIDATION_COMPLETED: 'VALIDATION_COMPLETED'
};